[[redirects]]
  from = "/"
  to = "https://highachieverdoneforyou.com/miracle-system-with-elaine-rocha?utm_source=ElaineRocha&utm_medium=social&utm_campaign=ElaineRocha&utm_term=ElaineRocha&utm_content=variable-date&affiliate=ElaineRocha"
  status = 301
  force = true
